# Generated by Django 4.2.3 on 2023-07-30 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Daraja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turi", models.CharField(max_length=2, verbose_name="turi")),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="telefon nomeri"),
                ),
                (
                    "email",
                    models.EmailField(max_length=400, verbose_name="Elektron pochta"),
                ),
                ("INN", models.CharField(max_length=20, verbose_name="INN")),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Company name")),
                ("rating", models.IntegerField(max_length=10, verbose_name="rating")),
                ("inn", models.CharField(max_length=100, verbose_name="INN")),
                ("izoh", models.TextField(verbose_name="Izoh")),
                (
                    "turi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.daraja"
                    ),
                ),
            ],
        ),
    ]
