# Generated by Django 4.2.3 on 2023-07-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="publish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="daraja",
            name="nomi",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Nomi"
            ),
        ),
    ]
